export const GET_ROOM_REGUEST = 'GET_ROOM_REGUEST';
export const GET_ROOM_SUCCESS = 'GET_ROOM_SUCCESS';
export const GET_ROOM_FAILED = 'GET_ROOM_FAILED';

export const GET_ROOMS_REGUEST = 'GET_ROOMS_REGUEST';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_FAILED = 'GET_ROOMS_FAILED';
